"""Shared constants for the initial migration slice."""

ALPHAEARTH_COLLECTION_ID = "GOOGLE/SATELLITE_EMBEDDING/V1/ANNUAL"
ALPHAEARTH_FIRST_YEAR = 2017
ALPHAEARTH_LAST_STABLE_YEAR = 2024
ALPHAEARTH_LAST_ALLOWED_YEAR = 2025
ALPHAEARTH_BAND_COUNT = 64
ALPHAEARTH_TARGET_RESOLUTION_M = 10.0
CROME_DEFAULT_LABEL_COLUMN = "lucode"
CROME_DEFAULT_GEOMETRY_COLUMN = "geometry"
